# netlify.toml

# First, explicitly define rules for your static files
[[redirects]]
from = "/sitemap.xml"
to = "/sitemap.xml"
status = 200
force = true

[[redirects]]
from = "/robots.txt"
to = "/robots.txt"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/sitemap.xml"
[headers.values]
Content-Type = "application/xml"
Cache-Control = "public, max-age=3600"

[[headers]]
for = "/robots.txt"
[headers.values]
Content-Type = "text/plain"
Cache-Control = "public, max-age=3600"
