const transpiledTheme = {
  light: {
    primaryColor: '#4A90E2',
    secondaryColor: '#FF6B6B',
    background: '#FFFFFF',
    text: '#333333',
    accentColor: '#64DDBB',
    neutral: '#c0cbd4',
    highlight: '#FFD700',
    white: '#ffffff',
    black: '#000000',
    gray: '#afafaf',
    transparent: 'transparent',
    separator: '#eaeaea',
    knobColor: '#2EBFD4',
    barColor: '#013F6A',
  },
  dark: {
    primaryColor: '#013F6A',
    secondaryColor: '#2EBFD4',
    background: '#090909',
    text: '#ffffff',
    accentColor: '#FF910F',
    neutral: '#757575',
    highlight: '#FFD700',
    white: '#ffffff',
    black: '#000000',
    gray: '#afafaf',
    transparent: 'transparent',
    knobColor: '#2EBFD4',
    barColor: '#afafaf',
  },
};

export default transpiledTheme;
